# Generated by Django 3.0.5 on 2020-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee_Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=120)),
                ('water_line', models.BooleanField()),
                ('code', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee_Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_type', models.CharField(max_length=120)),
                ('flaver', models.CharField(max_length=120)),
                ('pack_size', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120)),
            ],
        ),
    ]
